"""Input/output helpers for the TNDP solver."""

from __future__ import annotations

import json
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd

from config import CACHE_DIR, PROJ_EPSG
from .model import RouteSet


def load_phase2_demand() -> tuple[np.ndarray, gpd.GeoDataFrame]:
    """Load the dense OD matrix and participating stops.

    ``phase2/matrix_od.parquet`` is a sparse long-form matrix generated by the
    existing demand phase. Missing OD pairs are interpreted as zero.
    """
    stops_path = CACHE_DIR / "phase2" / "stops_matrix.parquet"
    od_path = CACHE_DIR / "phase2" / "matrix_od.parquet"
    if not stops_path.exists() or not od_path.exists():
        raise FileNotFoundError("Run Phase 1/2 first to create TNDP demand inputs")

    stops = gpd.read_parquet(stops_path).to_crs(PROJ_EPSG).reset_index(drop=True)
    od = pd.read_parquet(od_path)
    n = len(stops)
    matrix = np.zeros((n, n), dtype=float)
    if not od.empty:
        for row in od.itertuples(index=False):
            i, j = int(row.orig), int(row.dest)
            if 0 <= i < n and 0 <= j < n:
                matrix[i, j] = float(row.trips)
    return matrix, stops


def save_route_set(route_set: RouteSet, path: str | Path) -> Path:
    """Save a generated route set as a deterministic JSON artifact."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "n_routes": route_set.route_count(),
        "routes": [
            {
                "route_id": r.route_id,
                "frequency_vph": r.frequency_vph,
                "nodes": list(r.nodes),
            }
            for r in route_set.routes
        ],
    }
    target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return target
